name: Build

on:
  push:
    paths:
      - "data/**"
      - ".github/workflows/build.yml"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      LT_HOME: lt/languagetool
      PT_DICT_HOME: lt/portuguese-pos-dict
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ env.PT_DICT_HOME }}
        repository: ${{ env.GITHUB_ACTION_REPOSITORY }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Check Poetry config
      run: poetry check -C ${{ env.PT_DICT_HOME }}
    - name: Install dependencies
      run: poetry install -C ${{ env.PT_DICT_HOME }}
      env:
        POETRY_HTTP_BASIC_GITLAB_USERNAME: "lt-ai-package-registry"
        POETRY_HTTP_BASIC_GITLAB_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_GITLAB_PASSWORD }}
    - name: Set dictionary version
      run: |
        echo ${{ env.PT_DICT_HOME }}/.git/HEAD
        echo "PT_DICT_VERSION=$(git --work-tree=${{ env.PT_DICT_HOME }} describe --tags --abbrev=0 | sed 's/^v//g')" >> $GITHUB_ENV
    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.38"
    - name: Install Perl dependencies
      run: cpan install "Switch" "Text::Unaccent::PurePerl"
    - name: Install Hunspell
      run: apt-get install hunspell
    - name: Build POS tagging dictionary
      run: |
        cd "${{ env.PT_DICT_HOME }}" && bash ./pos_tagger_scripts/build-lt.sh && cd -
    - name: Build spelling dictionaries
      run: | 
        poetry run -C ${{ env.PT_DICT_HOME }} \
          python "${{ env.PT_DICT_HOME }}/pt_dict/scripts/build_spelling_dicts.py"
    - name: Checkout LT
      uses: actions/checkout@v3
      with:
        repository: languagetool-org/languagetool
        path: ${{ env.LT_HOME }}
        token: ${{ secrets.LT_OS_TOKEN }}
