name: Check PR Status

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  allchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/allcheckspassed@v1
