name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # TODO: uncomment once it's been tested
#    if: >
#      github.event.workflow_run.conclusion == 'success' &&
#      github.event.workflow_run.head_branch == 'main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Necessary since downloading artefacts with an 'overwrite' option is not supported
    - name: Empty out src directory
      run: rm -rf results/java-lt/src

    - name: Download artefact
      uses: actions/download-artifact@v3
      with:
        name: src
        path: results/java-lt/

    - name: Set dictionary version
      # TODO: remove 'test-' prefix!
      run: echo "PT_DICT_VERSION=test-$(git describe --tags --abbrev=0 | sed 's/^v//g')" >> $GITHUB_ENV

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    # This step makes sure that we're using the settings.xml file with env vars prepared for GPG and SonaType
    - name: Copy settings.xml to m2
      run: cp results/java-lt/settings.xml $HOME/.m2/settings.xml

    # Add your deployment steps here
    - name: Deploy
      env:
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      working-directory: results/java-lt
      run: mvn clean deploy -P release
