name: Test some BS

on:
  pull_request: {}

jobs:
  test-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Print labels and head commit msg
        run: |
          echo "LABELS: ${{ github.event.pull_request.labels.*.name }}"
          echo "HEAD COMMIT MSG: ${{ github.event.pull_request.head.commit.message }}"

      - name: Skip if 'skip lt test'
        if: > 
          (contains(github.event.pull_request.head.commit.message, '[skip lt test]') == false) ||
          (contains(github.event.pull_request.labels.*.name, 'skip_lt_test') == false)
        run: echo "Not skipping :("
